spring:
  application:
    name: chatbot-service
  profiles:
    active: ${CB_PROFILE:dev}

  ai:
    anthropic:
      api-key: ${CB_CLAUDE_API_KEY}

aws:
  region: ${CB_AWS_DYNAMODB_REGION}
  dynamodb:
    tables:
      chat-session: ${CB_AWS_DYNAMODB_CHAT_SESSION_TABLE:ChatSession}
      chat-message: ${CB_AWS_DYNAMODB_CHAT_MESSAGE_TABLE:ChatMessage}
