# .github/actions/common-build-steps/action.yml
name: 'Common Build Steps'
description: 'Checkout code, setup JDK, cache Maven, and extract version'

outputs:
  version:
    description: 'Maven project version'
    value: ${{ steps.maven_version.outputs.version }}
  artifact_id:
    description: 'Maven artifact ID'
    value: ${{ steps.maven_version.outputs.artifact_id }}

runs:
  using: 'composite'
  steps:
    # 1) Checkout the code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      shell: bash

    # 2) Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
      shell: bash

    # 3) Cache Maven packages
    - name: Cache Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
      shell: bash

    # 4) Compute version and artifact ID from Maven
    - name: Compute version from Maven
      id: maven_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT
        echo "Maven version: $VERSION"
        echo "Maven artifact ID: $ARTIFACT_ID"
      shell: bash
